[package]
name = "galaxy_save_data_json"
version = "0.1.0"
authors = ["ThatNintendoNerd"]
edition = "2024"

[dependencies]
clap.workspace = true
galaxy_save_data = { path = "../galaxy_save_data", features = ["serde"] }
serde_json.workspace = true
