---
name: Compile Release
on:
  release:
    types:
      - created
  workflow_dispatch: null
env:
  BUILD_PROFILE: release
jobs:
  build:
    strategy:
      matrix:
        include:
          - name: linux-x86_64
            platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: linux-arm64
            platform: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - name: windows-x86_64
            platform: windows-latest
            target: x86_64-pc-windows-msvc
          - name: windows-arm64
            platform: windows-latest
            target: aarch64-pc-windows-msvc
          - name: macos-x86_64
            platform: macos-latest
            target: x86_64-apple-darwin
          - name: macos-arm64
            platform: macos-latest
            target: aarch64-apple-darwin
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    env:
      ARTIFACT_DIR: target/${{ matrix.target }}/${{ env.BUILD_PROFILE }}
      ARTIFACT_NAME: ${{ github.repository }}-${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --profile ${{ env.BUILD_PROFILE }} --target ${{ matrix.target }}
      - name: Sign
        if: startsWith(matrix.platform, 'macos')
        run: |
          codesign -s - galaxy_save_data_json
          codesign -s - galaxy2_save_data_json
        working-directory: ${{ env.ARTIFACT_DIR }}
      - name: Create Artifact
        run: |
          if [[ startsWith(matrix.platform, 'windows') ]]; then
            Compress-Archive -path galaxy_save_data_json.exe, galaxy2_save_data_json.exe -destinationPath ${{ env.ARTIFACT_NAME }}.zip
          else
            zip ${{ env.ARTIFACT_NAME }}.zip galaxy_save_data_json galaxy2_save_data_json
          fi
        working-directory: ${{ env.ARTIFACT_DIR }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        working-directory: ${{ env.ARTIFACT_DIR }}
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}.zip
          if-no-files-found: error
      - name: Release Artifact
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ${{ env.ARTIFACT_DIR }}
        with:
          files: ${{ env.ARTIFACT_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
